const lang = {
  
  "EN": {
    "enterMovieOrTVShowName": "❌ Please enter a movie or TV show name!",
    "providechannellink": "❌ Provide a WhatsApp channel link",
    "invalidchannellink": "❌ Invalid channel link",
    "faildtofectchanneljid": "❌ Failed to fetch channel JID",
    "noResultsFound": "❌ No results found!",
    "invalidChoice": "❌ Invalid choice! Reply with a valid number.",
    "errorProcessingSelection": "❌ Error processing selection!",
    "errorFetchingMovieDetails": "❌ Error fetching movie details!",
    "needPnum": "📞 Please enter a phone number.",
    "errorMg": "*An error occurred, please try again later ❌*",
    "ownerMg": "🚫 *You are not authorized to use this command!*",
    "replyMg": "❗ *Please reply to a message*",
    "invalidReply": "❌ Invalid choice! Reply with ",
    "validLinkMg": "*Please provide a valid link*",
    "pfError": "❌ *Something went wrong fetching profile picture.*",
    "pfInvalid": "❌ *Invalid number.*",
    "pfNotFound": "❌ *Couldn't fetch profile picture. Maybe it's private.*",
    "pfMention": "🧑 *Mention a user or provide number to get their profile picture.*",
    "badApply": " : Invalid input! Please check format. ⛔",
    "rsMg": "✅ *Bot restarted successfully!*",
    "restartMg": "```♻️ Restarting bot...```",
    "dbReset": "*✅ DATABASE Resetting... Restarting bot*",
    "latestHave": "*You have already updated to the latest version. 🛠️*",
    "providePartsError": "😏 *Please provide both the first and second parts!*",
    "createPrankError": "❌ *Failed to create Read More prank.*",
    "pythonCodeError": "🔁 *Please quote valid Python code to compile and run.*",
    "pythonRunError": "❌ *Error occurred while running Python:*",
    "apiEndpointError": "❌ *Please provide an API endpoint!*",
    "invalidUrlError": "❌ *Invalid URL format!* \n\nPlease provide a valid HTTP/HTTPS URL.",
    "jsonApiError": "❌ *Please provide a JSON API endpoint!*",
    "testEndpointError": "❌ *Error loading test endpoints*",
    "provideSongNameError": "❌ *Please provide a song name!* \n\nExample: `.lyrics Shape of You`",
    "lyricsNotFoundError": "❌ *Lyrics not found for. Please check the song name and try again.*",
    "needCmd": "*Please provide a command ❓*",
    "needNumber": "*📞 Please enter a number!*",
    "pairCodeMis": "*❌ Error retrieving the pair code!*",
    "pairExpireAlert": "This code will expire in 1 minutes.",
    "pairExpireMg": "The pair code is now expired.",
    "queryMsg": "*Hellow i'am PRINCE-MDX AI System 🧠*",
    "noInputMsg": "🤖 Please ask me something! Usage: ",
    "unsupportedLangMsg": "❌ Unsupported language. Supported: ",
    "needOwner": "*👑 You must be the owner to use this command!*",
    "groupOnly": "*👥 This command can only be used in groups!*",
    "needAdmin": "*🚨 You must be an admin to use this command!*",
    "giveMeAdmin": "*🙏 Please grant me admin privileges!*",
    "provideMessageForTag": "❗ *Please provide a message to tag everyone.*",
    "userRemovedMessage": "*User has already been removed. 👨‍🔧*",
    "userRemovedFromGroup": "has been removed from the group. ✔️",
    "userNotInGroupError": "❌ *The user is not in this group.*",
    "removeUserReplyError": "❌ *Please reply to a user or provide their number to remove.*",
    "jokeFetchError": "❌ *Couldn't fetch a joke!* 😢",
    "questionFetchError": "❌ *Couldn't fetch a question!* 😕",
    "memeFetchError": "❌ *Couldn't fetch a meme!* 😢",
    "jokeLoadError": "❌ *Unable to load a joke!*",
    "questionPrompt": "❓ *Please ask a question.*\n\nExample: `.8ball Am I crazy?`",
    "magic8BallPrompt": "🎱 *Magic 8 Ball says:*\n\n*Question:*",
    "loveRequestPrompt": "❤️ *Please give two names.*\n\nExample: `.love John Mary`",
    "numreplyMg": "*🔢 Please reply with the number you want to select:*",
    "tiktokMg": "*❌ Please provide a valid TikTok URL!*",
    "tiktokFailMg": "*❌ Failed to download TikTok video.*",
    "ytMg": "*❌ Please provide a valid YouTube URL!*",
    "fbMg": "*❌ Please provide a valid Facebook URL!*",
    "fbFailMg": "*❌ Failed to download Facebook video.*",
    "twMg": "*❌ Please provide a valid Twitter URL!*",
    "twFailMg": "*❌ Failed to download Twitter video.*",
    "mfireMg": "*❌ Please provide a valid MediaFire URL!*",
    "igMg": "*❌ Please provide a valid Instagram URL!*",
    "githubMg": "*❌ Please provide a valid Github URL!*",
    "gdMg": "*❌ Please provide a valid Google Drive URL!*",
    "apkMg": "*❌ Please provide an APK name!*",
    "megaMg": "*❌ Please provide a valid Mega.nz URL!*",
    "mediaMg": "*✅ Media uploaded successfully ✅*",
    "notFoundMg": "*I couldn't find anything 📛*",
    "imgUsage": "❌ Enter a word to search for an image!\nUsage : ${config.PREFIX}img <Name>",
    "imgNotFound": "*❌ No image found for the word you entered!*",
    "imgFetchError": "*❌ An error occurred while searching for images.*",
    "wallUsage": "❌ *Please enter wallpaper type & search term!*\nExample: `.wallpaper mobile nature`\n`.wallpaper desktop cars`",
    "wallNotFound": "🚫 *No wallpapers found!* Try another search.",
    "wallFetchError": "⚠️ *Failed to download wallpapers! Try again later.*",
    "wallInvalidType": "❌ *Invalid type! Use 'mobile' or 'desktop'.*\nExample: `.wallpaper mobile city`",
    "validUrlMg": "*Please provide a valid link ❌*",
    "downMg": "*Starting to download...⬇*",
    "downUrlNotfound": "*Download link not found ❌*",
    "neddDirectUrl": "*📎 Please provide a valid direct file URL.*\n\n_Example",
    "errorMgMega": "❌ *Failed to download the MEGA file.* Please check the link or try again later.",
    "buttonTitle": "Click Here 📲",
    "needText": "*❓ Please provide a word to search.*",
    "disXvdl": "*This command has been disabled. ⛔️*",
    "pageUrlError": "🌐 *Provide a website URL!* \nExample:\n.pagesource https://example.com\n.pagesource https://example.com --json\n.pagesource https://example.com --json --tmsg",
    "fetchPageError": "❌ *Error fetching page:*",
    "fetchPageSourceError": "⚠️ *Failed to fetch the page source. Check the URL and try again.*",
    "fetchRomanticVideoError": "❌ *Failed to fetch romantic video.*",
    "fetchRomanticImagesError": "😢 *No romantic images found.*",
    "fetchMediaError": "❌ *Failed to fetch media.*",
    "fetchMediaApiError": "❌ *Check API key or folder access.*",
    "noMediaFoundError": "😢 *No media found in that category.*",
    "currencyUsage": "💰 *Usage:* ${config.PREFIX}currency 100 USD LKR",
    "currencyFailed": "❌ *Currency conversion failed!*",
    "shortUrlGenerated": "❌ *Enter a valid URL!*",
    "shortUrlFailed": "❌ *URL Shortening Failed!*",
    "validUrl": "*Usage:* \n\n${config.PREFIX} <Your Url>",
    "qrCodeFailed": "❌ *QR Code generation failed!*",
    "qrCodeEnterText": "❌ *Enter text to generate a QR Code!*",
    "qrCodeGenerated": "🔳 *QR Code Generated!*",
    "translateUsage": "🌍 *Usage:* ${config.PREFIX}translate si What's up?",
    "translateFailed": "❌ *Translation failed!*",
    "usageMessage": "🌐 *Usage:* ${config.PREFIX}whois example.com",
    "whoisFailedMessage": "❌ Whois lookup failed! No data found for this domain.",
    "passwordLengthError": "❌ Password length must be between 6 - 50 characters!",
    "passwordCountError": "❌ You can generate between 1 - 10 passwords!",
    "invalidSelectionMessage": "❌ *Invalid selection! Reply with a number between 1 - ${countEnd}*",
    "base64Usage": "📌 *Usage:* ${config.PREFIX}base64 encode Hello OR ${config.PREFIX}base64 decode SGVsbG8=",
    "base64InvalidAction": "⚠️ *Invalid action! Use 'encode' or 'decode'.*",
    "base64InvalidInput": "❌ *Invalid Base64 input!*",
    "fakeAddressFailed": "❌ Failed to generate a fake address.",
    "failMsg": "⚠️ *Please reply to an image!*",
    "usageMsg": "📌 *Usage:* ${config.PREFIX}img2url <image example>",
    "jsCodeNeed": "⚠️ *Please reply with a Jscode!*",
    "jsCodeError": "*This is not CommandJS code. ❌*",
    "tempMailError": "❌ *Error while generating temp mail.*",
    "tempMailAPIError": "❌ *Error occurred while communicating with TempMail API.*",
    "inboxEmptyError": "📭 *Inbox is empty or unable to",
    "inboxFetchError": "❌ *Something went wrong while fetching your inbox.*",
    "fetchingAddressMsg": "🔍 *Fetching temporary address...*",
    "fetchingPersonMsg": "🔍 *Fetching temporary person...*",
    "generatingVisaMsg": "🔍 *Generating Visa card...*",
    "generatingMasterCardMsg": "🔍 *Generating MasterCard card...*",
    "generatingProfileMsg": "🔍 *Fetching complete profile...*",
    "generatingCardMsg": "🔍 *Generating credit card...*",
    "unableToFetchAddress": "❌ Unable to fetch address. Please try again later.",
    "unableToFetchPerson": "❌ Unable to fetch person. Please try again later.",
    "errorGeneratingVisa": "❌ Error generating Visa card.",
    "errorGeneratingMasterCard": "❌ Error generating MasterCard card.",
    "errorGeneratingProfile": "❌ Error fetching profile.",
    "errorGeneratingCard": "❌ Error generating card.",
    "bankFetchError": "❌ *Unable to fetch bank information. Please try again later.*",
    "profileFetchError": "❌ *Unable to fetch complete profile. Please try again later.*",
    "errorMsg": "*An error occurred, please try again later ❌*",
    "invalidNumberMsg": "📞 Please provide a valid number or reply to a user.\n\nExample: `.whlink 0777123456 Hello`",
    "qrCaption": "📱 *Scan QR to open WhatsApp chat*",
    "weatherUsage": "*🌍 Please provide a location!*\nUsage: .weather Matara",
    "weatherErr": "❌ *Error retrieving weather info. Try again!*",
    "wikiUsage": "📖 *Please provide a topic to search!*\nUsage: .wiki SpaceX",
    "wikiNotFound": "❌ *No Wikipedia summary found!*",
    "wikiApiEr": "❌ *Error retrieving Wikipedia summary. Try again!*",
    "ipConfigErr": "❌ *Failed to fetch IP details! Check if the IP is valid.*",
    "needMath": "📌 Please provide a math expression or equation!\n\nExample:",
    "wrongMath": "❌ *Invalid equation or unsupported format. Please check.*",
    "mathMg": "🧮 *Math Evaluation*",
    "mathFunMg": "📚 *Supported math expression examples and function list*",
    "mathAdv": "➤ sqrt(25)      → Square Root\n➤ abs(-8)       → Absolute Value\n➤ log(100)      → Logarithm\n➤ factorial(5)  → 5!\n➤ gcd(20, 8)    → Greatest Common Divisor",
    "owner": "Owner",
    "ownerNb": "Owner Number",
    "platform": "Platform",
    "timeLang": "Time",
    "dateLang": "Date",
    "catLang": "Categories",
    "upLang": "Uptime",
    "ramLang": "RAM Usage",
    "versionLang": "Bot Version",
    "cpuLang": "CPU Speed",
    "engiLang": "Engine Version",
    "flagGameStarted": "🎌 *FLAG GAME STARTED*\n\n👤 Host: @{host}\n📝 Type *join* to participate\n⏰ 30 seconds to join",
"flagGameAlreadyRunning": "⚠️ Flag game already running.",
"flagGameNotRunning": "❌ No flag game is currently running.",
"flagGameHostOnlyStop": "❌ Only the host can stop the game.",
"flagGameStopped": "🛑 *Flag game stopped by host* @{host}",
"flagRoundText": "🎯 *FLAG ROUND {round}/{maxRounds}*\n\n🎌 {flag}\n\n🧩 *Options:*\n{options}\n\n@{player}, it's your turn! (30s to answer)\n📝 Reply with number (1-4) OR country name",
"flagCorrectAnswer": "🎉 *CORRECT!*\n\n🏳️ Country: {country}\n💰 +10 points to @{player}",
"flagWrongAnswer": "❌ Wrong answer! The correct answer was: *{country}*\nNext turn!",
"flagTimeExceeded": "⏰ @{player}, your time is exceeded!\n✅ Answer was: *{country}*",
"flagGameOver": "🏁 *FLAG GAME OVER*\n\n{scores}",
"flagAlreadyJoined": "⚠️ @{player}, you already joined!\n👥 Total players: {players}",
"flagJoined": "✅ @{player} joined the game!\n👥 Total players: {players}",
"flagGameCancelled": "❌ Game cancelled. Not enough players (min 2).",

"triviaGameStarted": "🧠 *TRIVIA GAME STARTED*\n\n👤 Host: @{host}\n📝 Type *join* to participate\n👥 Minimum players: 2\n⏰ 30 seconds to join",
"triviaGameAlreadyRunning": "⚠️ Trivia game already running!",
"triviaRoundText": "🧠 *TRIVIA ROUND {round}/{maxRounds}*\n\n*{question}*\n\n{options}\n\n@{player}, it's your turn! (30s to answer)\n📝 Reply with number (1-4) OR answer text",
"triviaCorrect": "🎉 Correct! +10 points to @{player}",
"triviaWrong": "❌ Wrong!\n✅ Answer: *{correct}*",
"triviaTimeExceeded": "⏰ @{player} your time is exceeded!\n✅ Answer: *{correct}*",
"triviaGameOver": "🏁 *TRIVIA GAME OVER*\n\n{scores}",
"triviaGameCancelled": "❌ Game cancelled. Minimum 2 players required.",

"guessGameStarted": "🔤 *GUESS WORD GAME STARTED*\n\n👤 Host: @{host}\n📝 Type *join* to participate\n👥 Minimum players: 2\n⏰ 30 seconds to join",
"guessGameAlreadyRunning": "⚠️ GuessWord game already running!",
"guessRoundText": "🔤 *GUESS WORD ROUND {round}/{maxRounds}*\n\n*Scrambled Word:* {scrambled}\n\n@{player}, it's your turn! (30s to answer)",
"guessCorrect": "🎉 Correct! +10 points to @{player}",
"guessWrong": "❌ Wrong!\n✅ Word was: *{word}*",
"guessTimeExceeded": "⏰ @{player} your time is exceeded!\n✅ Word was: *{word}*",
"guessGameOver": "🏁 *GUESS WORD GAME OVER*\n\n{scores}",
"guessGameCancelled": "❌ Game cancelled. Minimum 2 players required.",

"tttGameStart": "🎮 *TIC TAC TOE*\n\n@{player1} ❌ vs @{player2} ⭕\n\n{board}\n\n@{currentPlayer}'s turn",
"tttWinner": "🎉 *WINNER!*\n\n{board}\n\n@{player} wins!",
"tttDraw": "🤝 *DRAW*\n\n{board}",
"tttGameEnded": "🏳️ Game ended!\n@{opponent} wins by forfeit.",
"tttNoGame": "❌ You don't have an active TicTacToe game.",
"tttReplyToStart": "Reply to someone to start.",
"tttCantPlaySelf": "You can't play yourself.",
"tttPlayerAlreadyInGame": "One of the players is already in a game.",
"tttNotYourTurn": "Not your turn.",
"tttPositionUsed": "Position already used.",

"gameOnlyInGroups": "❌ This game only works in groups!",
"triviaOnlyInGroups": "❌ This game works only in groups!",
"guessOnlyInGroups": "❌ This game works only in groups!",
"adminsOnlyCmd": "*❌ Only admins can use this command!*",
"replyToMedia": "*❌ Reply to an image, video, audio, or text message!*",
"groupStatusSuccess": "*✅ Group status posted successfully!*",
"groupStatusFailed": "*❌ Failed to post group status!*",
"unsupportedMediaType": "*❌ Unsupported media type! Reply to an image, video, audio, or text.*"
  },

  "FR": {
    "enterMovieOrTVShowName": "❌ Veuillez entrer un nom de film ou d'émission TV!",
    "providechannellink": "❌ Veuillez fournir le lien du canal WhatsApp",
    "invalidchannellink": "❌ Lien du canal invalide",
    "faildtofectchanneljid": "❌ Impossible de récupérer le JID du canal",
    "noResultsFound": "❌ Aucun résultat trouvé!",
    "invalidChoice": "❌ Choix invalide! Répondez avec un numéro valide.",
    "errorProcessingSelection": "❌ Erreur lors du traitement de la sélection!",
    "errorFetchingMovieDetails": "❌ Erreur lors de la récupération des détails du film!",
    "needPnum": "📞 Veuillez entrer un numéro de téléphone.",
    "errorMg": "*Une erreur s'est produite, veuillez réessayer plus tard ❌*",
    "ownerMg": "🚫 *Vous n'êtes pas autorisé à utiliser cette commande!*",
    "replyMg": "❗ *Veuillez répondre à un message*",
    "invalidReply": "❌ Choix invalide! Répondez avec ",
    "validLinkMg": "*Veuillez fournir un lien valide*",
    "pfError": "❌ *Quelque chose s'est mal passé lors de la récupération de la photo de profil.*",
    "pfInvalid": "❌ *Numéro invalide.*",
    "pfNotFound": "❌ *Impossible de récupérer la photo de profil. Peut-être est-elle privée.*",
    "pfMention": "🧑 *Mentionnez un utilisateur ou fournissez un numéro pour obtenir sa photo de profil.*",
    "badApply": " : Entrée invalide! Veuillez vérifier le format. ⛔",
    "rsMg": "✅ *Bot redémarré avec succès!*",
    "restartMg": "```♻️ Redémarrage du bot...```",
    "dbReset": "*✅ Réinitialisation de la BASE DE DONNÉES... Redémarrage du bot*",
    "latestHave": "*Vous avez déjà mis à jour vers la dernière version. 🛠️*",
    "providePartsError": "😏 *Veuillez fournir les première et deuxième parties!*",
    "createPrankError": "❌ *Échec de la création du prank Read More.*",
    "pythonCodeError": "🔁 *Veuillez citer un code Python valide à compiler et exécuter.*",
    "pythonRunError": "❌ *Erreur lors de l'exécution de Python:*",
    "apiEndpointError": "❌ *Veuillez fournir un point de terminaison API!*",
    "invalidUrlError": "❌ *Format d'URL invalide!* \n\nVeuillez fournir une URL HTTP/HTTPS valide.",
    "jsonApiError": "❌ *Veuillez fournir un point de terminaison JSON API!*",
    "testEndpointError": "❌ *Erreur de chargement des points de terminaison de test*",
    "provideSongNameError": "❌ *Veuillez fournir un nom de chanson!* \n\nExemple: `.lyrics Shape of You`",
    "lyricsNotFoundError": "❌ *Paroles non trouvées pour. Veuillez vérifier le nom de la chanson et réessayer.*",
    "needCmd": "*Veuillez fournir une commande ❓*",
    "needNumber": "*📞 Veuillez entrer un numéro!*",
    "pairCodeMis": "*❌ Erreur lors de la récupération du code de jumelage!*",
    "pairExpireAlert": "Ce code expirera dans 1 minute.",
    "pairExpireMg": "Le code de jumelage est maintenant expiré.",
    "queryMsg": "*Bonjour, je suis le système d'IA PRINCE-MDX 🧠*",
    "noInputMsg": "🤖 Veuillez me demander quelque chose! Utilisation: ",
    "unsupportedLangMsg": "❌ Langue non supportée. Supportées: ",
    "needOwner": "*👑 Vous devez être le propriétaire pour utiliser cette commande!*",
    "groupOnly": "*👥 Cette commande ne peut être utilisée que dans les groupes!*",
    "needAdmin": "*🚨 Vous devez être administrateur pour utiliser cette commande!*",
    "giveMeAdmin": "*🙏 Veuillez me donner les privilèges d'administrateur!*",
    "provideMessageForTag": "❗ *Veuillez fournir un message pour taguer tout le monde.*",
    "userRemovedMessage": "*L'utilisateur a déjà été supprimé. 👨‍🔧*",
    "userRemovedFromGroup": "a été supprimé du groupe. ✔️",
    "userNotInGroupError": "❌ *L'utilisateur n'est pas dans ce groupe.*",
    "removeUserReplyError": "❌ *Veuillez répondre à un utilisateur ou fournir son numéro pour le supprimer.*",
    "jokeFetchError": "❌ *Impossible de récupérer une blague!* 😢",
    "questionFetchError": "❌ *Impossible de récupérer une question!* 😕",
    "memeFetchError": "❌ *Impossible de récupérer un mème!* 😢",
    "jokeLoadError": "❌ *Impossible de charger une blague!*",
    "questionPrompt": "❓ *Veuillez poser une question.*\n\nExemple: `.8ball Suis-je fou?`",
    "magic8BallPrompt": "🎱 *La boule magique 8 dit:*\n\n*Question:*",
    "loveRequestPrompt": "❤️ *Veuillez donner deux noms.*\n\nExemple: `.love Jean Marie`",
    "numreplyMg": "*🔢 Veuillez répondre avec le numéro que vous souhaitez sélectionner:*",
    "tiktokMg": "*❌ Veuillez fournir une URL TikTok valide!*",
    "tiktokFailMg": "*❌ Échec du téléchargement de la vidéo TikTok.*",
    "ytMg": "*❌ Veuillez fournir une URL YouTube valide!*",
    "fbMg": "*❌ Veuillez fournir une URL Facebook valide!*",
    "fbFailMg": "*❌ Échec du téléchargement de la vidéo Facebook.*",
    "twMg": "*❌ Veuillez fournir une URL Twitter valide!*",
    "twFailMg": "*❌ Échec du téléchargement de la vidéo Twitter.*",
    "mfireMg": "*❌ Veuillez fournir une URL MediaFire valide!*",
    "igMg": "*❌ Veuillez fournir une URL Instagram valide!*",
    "githubMg": "*❌ Veuillez fournir une URL Github valide!*",
    "gdMg": "*❌ Veuillez fournir une URL Google Drive valide!*",
    "apkMg": "*❌ Veuillez fournir un nom APK!*",
    "megaMg": "*❌ Veuillez fournir une URL Mega.nz valide!*",
    "mediaMg": "*✅ Média téléchargé avec succès ✅*",
    "notFoundMg": "*Je n'ai rien trouvé 📛*",
    "imgUsage": "❌ Entrez un mot pour rechercher une image!\nUtilisation : ${config.PREFIX}img <Nom>",
    "imgNotFound": "*❌ Aucune image trouvée pour le mot que vous avez entré!*",
    "imgFetchError": "*❌ Une erreur s'est produite lors de la recherche d'images.*",
    "wallUsage": "❌ *Veuillez entrer le type de fond d'écran et le terme de recherche!*\nExemple: `.wallpaper mobile nature`\n`.wallpaper desktop voitures`",
    "wallNotFound": "🚫 *Aucun fond d'écran trouvé!* Essayez une autre recherche.",
    "wallFetchError": "⚠️ *Échec du téléchargement des fonds d'écran! Réessayez plus tard.*",
    "wallInvalidType": "❌ *Type invalide! Utilisez 'mobile' ou 'desktop'.*\nExemple: `.wallpaper mobile ville`",
    "validUrlMg": "*Veuillez fournir un lien valide ❌*",
    "downMg": "*Début du téléchargement...⬇*",
    "downUrlNotfound": "*Lien de téléchargement non trouvé ❌*",
    "neddDirectUrl": "*📎 Veuillez fournir une URL de fichier direct valide.*\n\n_Exemple",
    "errorMgMega": "❌ *Échec du téléchargement du fichier MEGA.* Veuillez vérifier le lien ou réessayer plus tard.",
    "buttonTitle": "Cliquez ici 📲",
    "needText": "*❓ Veuillez fournir un mot à rechercher.*",
    "disXvdl": "*Cette commande a été désactivée. ⛔️*",
    "pageUrlError": "🌐 *Fournissez une URL de site web!* \nExemple:\n.pagesource https://exemple.com\n.pagesource https://exemple.com --json\n.pagesource https://exemple.com --json --tmsg",
    "fetchPageError": "❌ *Erreur lors de la récupération de la page:*",
    "fetchPageSourceError": "⚠️ *Échec de la récupération du code source de la page. Vérifiez l'URL et réessayez.*",
    "fetchRomanticVideoError": "❌ *Échec de la récupération de la vidéo romantique.*",
    "fetchRomanticImagesError": "😢 *Aucune image romantique trouvée.*",
    "fetchMediaError": "❌ *Échec de la récupération du média.*",
    "fetchMediaApiError": "❌ *Vérifiez la clé API ou l'accès au dossier.*",
    "noMediaFoundError": "😢 *Aucun média trouvé dans cette catégorie.*",
    "currencyUsage": "💰 *Utilisation:* ${config.PREFIX}currency 100 USD EUR",
    "currencyFailed": "❌ *Échec de la conversion de devises!*",
    "shortUrlGenerated": "❌ *Entrez une URL valide!*",
    "shortUrlFailed": "❌ *Échec du raccourcissement d'URL!*",
    "validUrl": "*Utilisation:* \n\n${config.PREFIX} <Votre URL>",
    "qrCodeFailed": "❌ *Échec de la génération du code QR!*",
    "qrCodeEnterText": "❌ *Entrez du texte pour générer un code QR!*",
    "qrCodeGenerated": "🔳 *Code QR généré!*",
    "translateUsage": "🌍 *Utilisation:* ${config.PREFIX}translate fr Quoi de neuf?",
    "translateFailed": "❌ *Échec de la traduction!*",
    "usageMessage": "🌐 *Utilisation:* ${config.PREFIX}whois exemple.com",
    "whoisFailedMessage": "❌ Échec de la recherche Whois! Aucune donnée trouvée pour ce domaine.",
    "passwordLengthError": "❌ La longueur du mot de passe doit être entre 6 et 50 caractères!",
    "passwordCountError": "❌ Vous pouvez générer entre 1 et 10 mots de passe!",
    "invalidSelectionMessage": "❌ *Sélection invalide! Répondez avec un numéro entre 1 et ${countEnd}*",
    "base64Usage": "📌 *Utilisation:* ${config.PREFIX}base64 encode Bonjour OU ${config.PREFIX}base64 decode SGVsbG8=",
    "base64InvalidAction": "⚠️ *Action invalide! Utilisez 'encode' ou 'decode'.*",
    "base64InvalidInput": "❌ *Entrée Base64 invalide!*",
    "fakeAddressFailed": "❌ Échec de la génération d'une fausse adresse.",
    "failMsg": "⚠️ *Veuillez répondre à une image!*",
    "usageMsg": "📌 *Utilisation:* ${config.PREFIX}img2url <exemple d'image>",
    "jsCodeNeed": "⚠️ *Veuillez répondre avec un code JS!*",
    "jsCodeError": "*Ce n'est pas un code CommandJS. ❌*",
    "tempMailError": "❌ *Erreur lors de la génération du mail temporaire.*",
    "tempMailAPIError": "❌ *Erreur survenue lors de la communication avec l'API TempMail.*",
    "inboxEmptyError": "📭 *La boîte de réception est vide ou impossible d'accéder",
    "inboxFetchError": "❌ *Quelque chose s'est mal passé lors de la récupération de votre boîte de réception.*",
    "fetchingAddressMsg": "🔍 *Récupération d'adresse temporaire...*",
    "fetchingPersonMsg": "🔍 *Récupération de personne temporaire...*",
    "generatingVisaMsg": "🔍 *Génération de carte Visa...*",
    "generatingMasterCardMsg": "🔍 *Génération de carte MasterCard...*",
    "generatingProfileMsg": "🔍 *Récupération du profil complet...*",
    "generatingCardMsg": "🔍 *Génération de carte de crédit...*",
    "unableToFetchAddress": "❌ Impossible de récupérer l'adresse. Veuillez réessayer plus tard.",
    "unableToFetchPerson": "❌ Impossible de récupérer la personne. Veuillez réessayer plus tard.",
    "errorGeneratingVisa": "❌ Erreur lors de la génération de la carte Visa.",
    "errorGeneratingMasterCard": "❌ Erreur lors de la génération de la carte MasterCard.",
    "errorGeneratingProfile": "❌ Erreur lors de la récupération du profil.",
    "errorGeneratingCard": "❌ Erreur lors de la génération de la carte.",
    "bankFetchError": "❌ *Impossible de récupérer les informations bancaires. Veuillez réessayer plus tard.*",
    "profileFetchError": "❌ *Impossible de récupérer le profil complet. Veuillez réessayer plus tard.*",
    "errorMsg": "*Une erreur s'est produite, veuillez réessayer plus tard ❌*",
    "invalidNumberMsg": "📞 Veuillez fournir un numéro valide ou répondre à un utilisateur.\n\nExemple: `.whlink 0777123456 Bonjour`",
    "qrCaption": "📱 *Scannez le QR pour ouvrir le chat WhatsApp*",
    "weatherUsage": "*🌍 Veuillez fournir un lieu!*\nUtilisation: .weather Paris",
    "weatherErr": "❌ *Erreur lors de la récupération des informations météo. Réessayez!*",
    "wikiUsage": "📖 *Veuillez fournir un sujet à rechercher!*\nUtilisation: .wiki SpaceX",
    "wikiNotFound": "❌ *Aucun résumé Wikipedia trouvé!*",
    "wikiApiEr": "❌ *Erreur lors de la récupération du résumé Wikipedia. Réessayez!*",
    "ipConfigErr": "❌ *Échec de la récupération des détails IP! Vérifiez si l'IP est valide.*",
    "needMath": "📌 Veuillez fournir une expression ou équation mathématique!\n\nExemple:",
    "wrongMath": "❌ *Équation invalide ou format non supporté. Veuillez vérifier.*",
    "mathMg": "🧮 *Évaluation mathématique*",
    "mathFunMg": "📚 *Exemples d'expressions mathématiques supportées et liste de fonctions*",
    "mathAdv": "➤ sqrt(25)      → Racine carrée\n➤ abs(-8)       → Valeur absolue\n➤ log(100)      → Logarithme\n➤ factorial(5)  → 5!\n➤ gcd(20, 8)    → Plus grand commun diviseur",
    "owner": "Propriétaire",
    "ownerNb": "Numéro du propriétaire",
    "platform": "Plateforme",
    "timeLang": "Heure",
    "dateLang": "Date",
    "catLang": "Catégories",
    "upLang": "Temps de fonctionnement",
    "ramLang": "Utilisation RAM",
    "versionLang": "Version du bot",
    "cpuLang": "Vitesse CPU",
    "engiLang": "Version du moteur",
    "flagGameStarted": "🎌 *JEU DE DRAPEAUX DÉMARRÉ*\n\n👤 Hôte : @{host}\n📝 Tapez *join* pour participer\n⏰ 30 secondes pour rejoindre",
"flagGameAlreadyRunning": "⚠️ Un jeu de drapeaux est déjà en cours.",
"flagGameNotRunning": "❌ Aucun jeu de drapeaux n'est actuellement en cours.",
"flagGameHostOnlyStop": "❌ Seul l'hôte peut arrêter le jeu.",
"flagGameStopped": "🛑 *Jeu de drapeaux arrêté par l'hôte* @{host}",
"flagRoundText": "🎯 *TOUR DE DRAPEAU {round}/{maxRounds}*\n\n🎌 {flag}\n\n🧩 *Options :*\n{options}\n\n@{player}, c'est votre tour ! (30s pour répondre)\n📝 Répondez avec le numéro (1-4) OU le nom du pays",
"flagCorrectAnswer": "🎉 *CORRECT !*\n\n🏳️ Pays : {country}\n💰 +10 points pour @{player}",
"flagWrongAnswer": "❌ Mauvaise réponse ! La bonne réponse était : *{country}*\nTour suivant !",
"flagTimeExceeded": "⏰ @{player}, votre temps est écoulé !\n✅ La réponse était : *{country}*",
"flagGameOver": "🏁 *JEU DE DRAPEAUX TERMINÉ*\n\n{scores}",
"flagAlreadyJoined": "⚠️ @{player}, vous avez déjà rejoint !\n👥 Total joueurs : {players}",
"flagJoined": "✅ @{player} a rejoint le jeu !\n👥 Total joueurs : {players}",
"flagGameCancelled": "❌ Jeu annulé. Pas assez de joueurs (min 2).",

"triviaGameStarted": "🧠 *JEU DE CULTURE GÉNÉRALE DÉMARRÉ*\n\n👤 Hôte : @{host}\n📝 Tapez *join* pour participer\n👥 Minimum 2 joueurs\n⏰ 30 secondes pour rejoindre",
"triviaGameAlreadyRunning": "⚠️ Un jeu de culture générale est déjà en cours !",
"triviaRoundText": "🧠 *TOUR DE CULTURE GÉNÉRALE {round}/{maxRounds}*\n\n*{question}*\n\n{options}\n\n@{player}, c'est votre tour ! (30s pour répondre)\n📝 Répondez avec le numéro (1-4) OU le texte de la réponse",
"triviaCorrect": "🎉 Correct ! +10 points pour @{player}",
"triviaWrong": "❌ Faux !\n✅ Réponse : *{correct}*",
"triviaTimeExceeded": "⏰ @{player} votre temps est écoulé !\n✅ Réponse : *{correct}*",
"triviaGameOver": "🏁 *JEU DE CULTURE GÉNÉRALE TERMINÉ*\n\n{scores}",
"triviaGameCancelled": "❌ Jeu annulé. Minimum 2 joueurs requis.",

"guessGameStarted": "🔤 *JEU DE MOTS MÊLÉS DÉMARRÉ*\n\n👤 Hôte : @{host}\n📝 Tapez *join* pour participer\n👥 Minimum 2 joueurs\n⏰ 30 secondes pour rejoindre",
"guessGameAlreadyRunning": "⚠️ Un jeu de mots mêlés est déjà en cours !",
"guessRoundText": "🔤 *TOUR DE MOTS MÊLÉS {round}/{maxRounds}*\n\n*Mot mêlé :* {scrambled}\n\n@{player}, c'est votre tour ! (30s pour répondre)",
"guessCorrect": "🎉 Correct ! +10 points pour @{player}",
"guessWrong": "❌ Faux !\n✅ Le mot était : *{word}*",
"guessTimeExceeded": "⏰ @{player} votre temps est écoulé !\n✅ Le mot était : *{word}*",
"guessGameOver": "🏁 *JEU DE MOTS MÊLÉS TERMINÉ*\n\n{scores}",
"guessGameCancelled": "❌ Jeu annulé. Minimum 2 joueurs requis.",

"tttGameStart": "🎮 *MORPION*\n\n@{player1} ❌ contre @{player2} ⭕\n\n{board}\n\n@{currentPlayer} c'est votre tour",
"tttWinner": "🎉 *GAGNANT !*\n\n{board}\n\n@{player} gagne !",
"tttDraw": "🤝 *MATCH NUL*\n\n{board}",
"tttGameEnded": "🏳️ Jeu terminé !\n@{opponent} gagne par forfait.",
"tttNoGame": "❌ Vous n'avez pas de partie de Morpion active.",
"tttReplyToStart": "Répondez à quelqu'un pour commencer.",
"tttCantPlaySelf": "Vous ne pouvez pas jouer contre vous-même.",
"tttPlayerAlreadyInGame": "Un des joueurs est déjà dans une partie.",
"tttNotYourTurn": "Ce n'est pas votre tour.",
"tttPositionUsed": "Position déjà utilisée.",

"gameOnlyInGroups": "❌ Ce jeu ne fonctionne que dans les groupes !",
"triviaOnlyInGroups": "❌ Ce jeu ne fonctionne que dans les groupes !",
"guessOnlyInGroups": "❌ Ce jeu ne fonctionne que dans les groupes !",
"adminsOnlyCmd": "*❌ Seuls les administrateurs peuvent utiliser cette commande !*",
"replyToMedia": "*❌ Répondez à une image, vidéo, audio ou message texte !*",
"groupStatusSuccess": "*✅ Statut du groupe publié avec succès !*",
"groupStatusFailed": "*❌ Échec de la publication du statut du groupe !*",
"unsupportedMediaType": "*❌ Type de média non supporté ! Répondez à une image, vidéo, audio ou texte.*"
  }
};

export default lang;
